In [1]:
import pandas as pd
import random
import json

# FigQA

In [95]:
figqa = pd.read_csv("./../data/fig_qa.csv")
figqa.head()

,startphrase,ending1,ending2,labels,valid,qid
0,Her word had the strength of titanium.,Her promises can be believed.,Her promises cannot be trusted.,0,1,10
1,Her word had the strength of a wine glass.,Her promises can be believed.,Her promises cannot be trusted.,1,1,10
2,His kisses have the passion of lovers meeting ...,His kisses are demonstrative and intense.,His kiss is unemotional.,0,1,11
3,His kisses have the passion of a couple in a l...,His kisses are demonstrative and intense.,His kiss is unemotional.,1,1,11
4,This winter is as cold as my mother-in-law tow...,It's very cold,It's pretty warm,0,1,14

## Agreement Disagreement

In [96]:
ans = []
ops = []
cts = []
qid = []
for index,row in figqa.iterrows():
    ct1 = ""
    ct1 += "Speaker_1: " + row['startphrase'] + "\n"
    ct2 = ct1 + "Speaker_2: " + row['ending2']
    ct1 += "Speaker_2: " + row['ending1']
    options = ['Speaker_2 agrees with Speaker_1','Speaker_2 disagrees with Speaker_1']
    if row['labels']==0:
        ans.append(options[0])
        ans.append(options[1])
    else:
        ans.append(options[1])
        ans.append(options[0])
    ops.extend([options]*2)
    cts.extend([ct1,ct2])
    qid.extend([row['qid']]*2)

In [97]:
fig_agree = pd.DataFrame()
fig_agree['correct answer'] = ans
fig_agree['options'] = ops
fig_agree['pretext'] = cts
fig_agree['qid'] = qid
fig_agree.head()

,correct answer,options,pretext,qid
0,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: Her word had the strength of titani...,10
1,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: Her word had the strength of titani...,10
2,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: Her word had the strength of a wine...,10
3,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: Her word had the strength of a wine...,10
4,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: His kisses have the passion of love...,11

In [98]:
cts[0],ops[0],ans[0]

('Speaker_1: Her word had the strength of titanium.\nSpeaker_2: Her promises can be believed.',
 ['Speaker_2 agrees with Speaker_1', 'Speaker_2 disagrees with Speaker_1'],
 'Speaker_2 agrees with Speaker_1')

In [99]:
narrowed_df = pd.DataFrame()
sampled_indices = []
for cat in fig_agree['correct answer'].unique():
    cat_df = fig_agree[fig_agree['correct answer'] == cat]
    sampled_cat_df = cat_df.sample(n = 1000, random_state=42)
    narrowed_df = pd.concat([narrowed_df,sampled_cat_df])
    sampled_indices.extend(sampled_cat_df.index)

In [100]:
len(set(narrowed_df['qid']))

931

In [101]:
len(narrowed_df)

2000

In [102]:
narrowed_df

,correct answer,options,pretext,qid
14024,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: The argument was as logical as a ra...,X2777
636,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: The defense's argument had the simp...,392
5379,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: My legs are Tree stalks\nSpeaker_2:...,X615
12423,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: The watermelon was as sweet as a ch...,X2376
13179,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: They felt the emotion as a warm bat...,X2565
...,...,...,...,...
6820,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: The woman was as explosive as a fat...,X976
11789,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: She is worth 10 XP\nSpeaker_2: She ...,X2218
4490,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: This razor is sharp like a pillow\n...,X393
6950,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: my mustache is a sphynx cat\nSpeake...,X1008
13678,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: The sun is happy\nSpeaker_2: The we...,X2690

In [103]:
shuffled_df = narrowed_df.sample(frac=1, random_state=42)  # Set random_state for reproducibility
shuffled_df.reset_index(drop=True, inplace=True)

In [104]:
shuffled_df

,correct answer,options,pretext,qid
0,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: The chair was comfortable like a pi...,X1607
1,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: the man's idea had the creativity o...,X3149
2,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: The girl's taste was as rich as cha...,1367
3,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: The student has the insight of a go...,873
4,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: Her eyes are real intoxication.\nSp...,X700
...,...,...,...,...
1995,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: The shirt was as bright as a dark c...,X2046
1996,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: I have the face of a model\nSpeaker...,X363
1997,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: The chair was comfortable like a pi...,X1607
1998,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: The lizard was as ugly as a dead sq...,X2571
1999,Speaker_2 disagrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 di...",Speaker_1: The cracker was as crunchy as Bitin...,X2733

In [105]:
shuffled_df.to_csv("./../global_datasets/task_4.csv")

## Sarcasm

In [106]:
addon = ['Yeah, ', 'True, ', 'Of course, ', 'Yes, ']

In [107]:
ans = []
ops = []
cts = []
qid = []
for index,row in figqa.iterrows():
    ct1 = "Speaker_1: " + row['ending1'] + "\n"
    ct2 = "Speaker_1: " + row['ending2'] + "\n"
    ct1 += "Speaker_2: " + random.choice(addon) + row['startphrase']
    ct2 += "Speaker_2: " + random.choice(addon) + row['startphrase']
    options = ['Speaker_2 agrees with Speaker_1','Speaker_2 is being sarcastic with Speaker_1']
    if row['labels']==0:
        ans.append(options[0])
        ans.append(options[1])
    else:
        ans.append(options[1])
        ans.append(options[0])
    ops.extend([options]*2)
    cts.extend([ct1,ct2])
    qid.extend([row['qid']]*2)

In [108]:
fig_sar = pd.DataFrame()
fig_sar['correct answer'] = ans
fig_sar['options'] = ops
fig_sar['pretext'] = cts
fig_sar['qid'] = qid
fig_sar.head()

,correct answer,options,pretext,qid
0,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: Her promises can be believed.\nSpea...,10
1,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: Her promises cannot be trusted.\nSp...,10
2,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: Her promises can be believed.\nSpea...,10
3,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: Her promises cannot be trusted.\nSp...,10
4,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: His kisses are demonstrative and in...,11

In [109]:
j = 38
print(cts[j])
print(ops[j])
print(ans[j])

Speaker_1: Money is good
Speaker_2: Yes, Money is a murderer
['Speaker_2 agrees with Speaker_1', 'Speaker_2 is being sarcastic with Speaker_1']
Speaker_2 is being sarcastic with Speaker_1

In [110]:
narrowed_df = pd.DataFrame()
sampled_indices = []
for cat in fig_sar['correct answer'].unique():
    cat_df = fig_sar[fig_sar['correct answer'] == cat]
    sampled_cat_df = cat_df.sample(n = 1000, random_state=42)
    narrowed_df = pd.concat([narrowed_df,sampled_cat_df])
    sampled_indices.extend(sampled_cat_df.index)

In [111]:
len(set(narrowed_df['qid']))

931

In [112]:
len(narrowed_df)

2000

In [113]:
narrowed_df

,correct answer,options,pretext,qid
14024,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The argument was not logical\nSpeak...,X2777
636,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The argument was complicated.\nSpea...,392
5379,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: My legs are thick and large\nSpeake...,X615
12423,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The watermelon was sweet\nSpeaker_2...,X2376
13179,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The emotion felt gentle and pleasan...,X2565
...,...,...,...,...
6820,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The woman was very explosive.\nSpea...,X976
11789,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: She is experienced.\nSpeaker_2: Yes...,X2218
4490,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: This razor is very sharp\nSpeaker_2...,X393
6950,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: my mustache is bushy and long\nSpea...,X1008
13678,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The weather is really hot!\nSpeaker...,X2690

In [114]:
shuffled_df = narrowed_df.sample(frac=1, random_state=42)  # Set random_state for reproducibility
shuffled_df.reset_index(drop=True, inplace=True)

In [115]:
shuffled_df

,correct answer,options,pretext,qid
0,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The chair was uncomfortable.\nSpeak...,X1607
1,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The idea was very creative\nSpeaker...,X3149
2,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The girl had cheap and tacky taste....,1367
3,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The student is unwise\nSpeaker_2: O...,873
4,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: Her eyes are ugly.\nSpeaker_2: True...,X700
...,...,...,...,...
1995,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The shirt was bright\nSpeaker_2: Of...,X2046
1996,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: My face is hideous\nSpeaker_2: True...,X363
1997,Speaker_2 agrees with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The chair was very comfortable.\nSp...,X1607
1998,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...","Speaker_1: it was cute\nSpeaker_2: True, The l...",X2571
1999,Speaker_2 is being sarcastic with Speaker_1,"[Speaker_2 agrees with Speaker_1, Speaker_2 is...",Speaker_1: The cracker made loud crunching noi...,X2733

In [116]:
shuffled_df.to_csv("./../global_datasets/task_5.csv")

# Flute

In [22]:
!wget https://raw.githubusercontent.com/tuhinjubcse/model-in-the-loop-fig-lang/main/idiomNLI/idiom_train.jsonl
!wget https://raw.githubusercontent.com/tuhinjubcse/model-in-the-loop-fig-lang/main/metaphorNLI/metaphor_train.jsonl
!wget https://raw.githubusercontent.com/tuhinjubcse/model-in-the-loop-fig-lang/main/SarcasmNLI/sarcasm_train.jsonl
!wget https://raw.githubusercontent.com/tuhinjubcse/model-in-the-loop-fig-lang/main/simileNLI/simile_train.jsonl

--2023-09-11 21:44:05--  https://raw.githubusercontent.com/tuhinjubcse/model-in-the-loop-fig-lang/main/idiomNLI/idiom_train.jsonl
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 746690 (729K) [text/plain]
Saving to: ‘idiom_train.jsonl’

idiom_train.jsonl   100%[===================>] 729.19K  2.91MB/s    in 0.2s

2023-09-11 21:44:05 (2.91 MB/s) - ‘idiom_train.jsonl’ saved [746690/746690]

--2023-09-11 21:44:06--  https://raw.githubusercontent.com/tuhinjubcse/model-in-the-loop-fig-lang/main/metaphorNLI/metaphor_train.jsonl
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 381917 (373K) [text/plain]
Saving to: ‘metaphor_train.jsonl’

metaphor_train.json 100%[===================>] 372.97K  2.22MB/s    in 0.2s

2023-09-11 21:44:06 (2.22 MB/s) - ‘metaphor_train.jsonl’ saved [381917/381917]

--2023-09-11 21:44:06--  https://raw.githubusercontent.com/tuhinjubcse/model-in-the-loop-fig-lang/main/SarcasmNLI/sarcasm_train.jsonl
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1358730 (1.3M) [text/plain]
Saving to: ‘sarcasm_train.jsonl’

sarcasm_train.jsonl 100%[===================>]   1.29M  4.69MB/s    in 0.3s

2023-09-11 21:44:07 (4.69 MB/s) - ‘sarcasm_train.jsonl’ saved [1358730/1358730]

--2023-09-11 21:44:07--  https://raw.githubusercontent.com/tuhinjubcse/model-in-the-loop-fig-lang/main/simileNLI/simile_train.jsonl
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 402910 (393K) [text/plain]
Saving to: ‘simile_train.jsonl’

simile_train.jsonl  100%[===================>] 393.47K  --.-KB/s    in 0.06s

2023-09-11 21:44:07 (6.83 MB/s) - ‘simile_train.jsonl’ saved [402910/402910]

In [125]:
flute = pd.DataFrame()

In [126]:
fpath = "./idiom_train.jsonl"
data_list = {}
with open(fpath, "r") as json_file:
    for line in json_file:
        data = json.loads(line)
        if data['id'] not in list(data_list.keys()):
            data_list[data['id']] = {
                'hypothesis' : data['hypothesis'],
                'meaning1' : data['premise'],
                'done' : 'no'
            }
            if data['label']=='Entailment':
                data_list[data['id']]['correct_answer'] = 'meaning1'
                data_list[data['id']]['entailed_exp'] = data['explanation']
            else:
                data_list[data['id']]['correct_answer'] = 'meaning2'
                data_list[data['id']]['contradictory_exp'] = data['explanation']
        else:
            if data_list[data['id']]['correct_answer'] == 'meaning1':
                if data['label'] == 'Contradiction':
                    data_list[data['id']]['meaning2'] = data['premise']
                    data_list[data['id']]['contradictory_exp'] = data['explanation']
                    data_list[data['id']]['done'] = 'yes'
            else:
                if data['label'] == 'Entailment':
                    data_list[data['id']]['meaning1'] = data['premise']
                    data_list[data['id']]['entailed_exp'] = data['explanation']
                    data_list[data['id']]['done'] = 'yes'
df = pd.DataFrame.from_dict(data_list, orient='index')
flute = pd.concat([flute,df])

In [127]:
fpath = "./metaphor_train.jsonl"
data_list = {}
with open(fpath, "r") as json_file:
    for line in json_file:
        data = json.loads(line)
        if data['id'] not in list(data_list.keys()):
            data_list[data['id']] = {
                'hypothesis' : data['hypothesis'],
                'meaning1' : data['premise'],
                'done' : 'no'
            }
            if data['label']=='Entailment':
                data_list[data['id']]['correct_answer'] = 'meaning1'
                data_list[data['id']]['entailed_exp'] = data['explanation']
            else:
                data_list[data['id']]['correct_answer'] = 'meaning2'
                data_list[data['id']]['contradictory_exp'] = data['explanation']
        else:
            if data_list[data['id']]['correct_answer'] == 'meaning1':
                if data['label'] == 'Contradiction':
                    data_list[data['id']]['meaning2'] = data['premise']
                    data_list[data['id']]['contradictory_exp'] = data['explanation']
                    data_list[data['id']]['done'] = 'yes'
            else:
                if data['label'] == 'Entailment':
                    data_list[data['id']]['meaning1'] = data['premise']
                    data_list[data['id']]['entailed_exp'] = data['explanation']
                    data_list[data['id']]['done'] = 'yes'
df = pd.DataFrame.from_dict(data_list, orient='index')
flute = pd.concat([flute,df])

In [128]:
fpath = "./sarcasm_train.jsonl"
data_list = {}
with open(fpath, "r") as json_file:
    for line in json_file:
        data = json.loads(line)
        if data['id'] not in list(data_list.keys()):
            data_list[data['id']] = {
                'hypothesis' : data['hypothesis'],
                'meaning1' : data['premise'],
                'done' : 'no'
            }
            if data['label']=='Entailment':
                data_list[data['id']]['correct_answer'] = 'meaning1'
                data_list[data['id']]['entailed_exp'] = data['explanation']
            else:
                data_list[data['id']]['correct_answer'] = 'meaning2'
                data_list[data['id']]['contradictory_exp'] = data['explanation']
        else:
            if data_list[data['id']]['correct_answer'] == 'meaning1':
                if data['label'] == 'Contradiction':
                    data_list[data['id']]['meaning2'] = data['premise']
                    data_list[data['id']]['contradictory_exp'] = data['explanation']
                    data_list[data['id']]['done'] = 'yes'
            else:
                if data['label'] == 'Entailment':
                    data_list[data['id']]['meaning1'] = data['premise']
                    data_list[data['id']]['entailed_exp'] = data['explanation']
                    data_list[data['id']]['done'] = 'yes'
df = pd.DataFrame.from_dict(data_list, orient='index')
flute = pd.concat([flute,df])

In [129]:
fpath = "./simile_train.jsonl"
data_list = {}
with open(fpath, "r") as json_file:
    for line in json_file:
        data = json.loads(line)
        if data['id'] not in list(data_list.keys()):
            data_list[data['id']] = {
                'hypothesis' : data['hypothesis'],
                'meaning1' : data['premise'],
                'done' : 'no'
            }
            if data['label']=='Entailment':
                data_list[data['id']]['correct_answer'] = 'meaning1'
                data_list[data['id']]['entailed_exp'] = data['explanation']
            else:
                data_list[data['id']]['correct_answer'] = 'meaning2'
                data_list[data['id']]['contradictory_exp'] = data['explanation']
        else: 
            if data_list[data['id']]['correct_answer'] == 'meaning1':
                if data['label'] == 'Contradiction':
                    data_list[data['id']]['meaning2'] = data['premise']
                    data_list[data['id']]['contradictory_exp'] = data['explanation']
                    data_list[data['id']]['done'] = 'yes'
            else:
                if data['label'] == 'Entailment':
                    data_list[data['id']]['meaning1'] = data['premise']
                    data_list[data['id']]['entailed_exp'] = data['explanation']
                    data_list[data['id']]['done'] = 'yes'
df = pd.DataFrame.from_dict(data_list, orient='index')
flute = pd.concat([flute,df])

In [130]:
df['correct_answer'].value_counts()

correct_answer
meaning1    625
Name: count, dtype: int64

In [131]:
len(flute)

3388

In [132]:
flute['correct_answer'].value_counts()

correct_answer
meaning1    3163
meaning2     225
Name: count, dtype: int64

In [133]:
flute = flute.dropna()
flute.reset_index(drop=True, inplace=True)

In [134]:
filtered_df = flute[~(flute['meaning1'].str.contains(' not ') | flute['meaning2'].str.contains(' not '))]
len(filtered_df)

2716

In [135]:
filtered_df

,hypothesis,meaning1,done,correct_answer,entailed_exp,meaning2,contradictory_exp
0,"To add insult to injury, a boy was leading a h...","To make things worse, a boy was leading a hand...",yes,meaning1,To add insult to injury means to make a bad si...,"In order to make things a lot better, a boy wa...",To add insult to injury means to make a bad si...
2,"Oh, you know how it is, mother, when you spend...","Oh, you know how it is, mother, when you spend...",yes,meaning1,"An old flame is a former lover, so spending th...","Oh, you know how it is, mother, when you spend...","An old flame is a former lover, but spending t..."
3,"Definitely a good person, but one could tell s...","Definitely a good person, but one could tell s...",yes,meaning1,"And all that jazz means and everything else, s...","Definitely a good person, but one could tell s...","And all that jazz means and everything else, b..."
4,"To ask what's it like to be a warden in d.c., ...","To ask what's it like to be a warden in d.c., ...",yes,meaning1,"And all that jazz means and everything else, s...","To ask what's it like to be a warden in d.c., ...","And all that jazz means and everything else, b..."
7,He would smash into it at full tilt.,He would smash into it as fast as he could.,yes,meaning1,To be at full tilt means to be going as fast a...,He would smash into it as slowly as he could.,To be at full tilt means to be going as fast a...
...,...,...,...,...,...,...,...
3130,You're loyal as Benedict Arnold,You're disloyal,yes,meaning1,"Benedict Arnold was a traitor, so to say someo...",You're loyal,"Benedict Arnold was a traitor, so being as loy..."
3131,The cat was as white as charcoal,The cat was black,yes,meaning1,White and black are opposite colors on the col...,The cat was white,"Charcoal is a black material, not a white one"
3132,You're as thin as a balloon,You're fat,yes,meaning1,"A balloon is filled with air, and is therefore...",You're thin,"A balloon is round, so saying someone is as th..."
3133,The woman was as useful as People Magazine,The woman was useless.,yes,meaning1,People Magazine is a magazine full of pictures...,The woman was useful.,"People Magazine is not useful, as it is a goss..."
3134,The conversation was as juicy as a business me...,The conversation was very dull.,yes,meaning1,A business meeting is a formal occasion where ...,The conversation was very juicy.,A business meeting would not be considered a j...

In [136]:
filtered_df = filtered_df[filtered_df['meaning1']!=filtered_df['meaning2']].reset_index(drop=True)
len(filtered_df)

1770

In [137]:
new_df = pd.DataFrame()
new_df['hypothesis'] = filtered_df['hypothesis']
new_df['entailed_exp'] = filtered_df['entailed_exp']
new_df['contradictory_exp'] = filtered_df['contradictory_exp']
new_df['correct_answer'] = filtered_df['meaning1']
def shuffle_meanings(row):
    meanings = [row['meaning1'], row['meaning2']]
    random.shuffle(meanings)
    return pd.Series(meanings, index=['meaning1', 'meaning2'])
new_df[['meaning1', 'meaning2']] = filtered_df.apply(shuffle_meanings, axis=1)

In [140]:
filtered_df = new_df.reset_index(drop=True)

In [141]:
j = 50
print("hyp : ",filtered_df['hypothesis'][j])
print("option a : ",filtered_df['meaning1'][j])
print("option b : ",filtered_df['meaning2'][j])
print("correct answer : ",filtered_df['correct_answer'][j])
print("exp1 : ",filtered_df['entailed_exp'][j])
print("exp2 : ",filtered_df['contradictory_exp'][j])

hyp :  Mike nods and trots over c better late than never.
option a :  Mike nods and trots over c although it would have been better if it happened earlier, at least it's happening now.
option b :  Mike nods and trots over c  because it's happening now and there's no need for it to have happened earlier.
correct answer :  Mike nods and trots over c although it would have been better if it happened earlier, at least it's happening now.
exp1 :  The idiom better late than never means that the delayed occurrence or achievement of something is better than it not happening at all, which is what is happening in this sentence.
exp2 :  The idiom better late than never means that the delayed occurrence or achievement of something is better than it not happening at all, but this sentence describes a situation where there is no need for it to have happened earlier.

In [142]:
df_final = pd.DataFrame()
df_final['pretext'] = 'Sentence : ' + filtered_df['hypothesis']
df_final['options'] = [[filtered_df['meaning1'][i],filtered_df['meaning2'][i]] for i in range(len(filtered_df))]
df_final['correct answer'] = filtered_df['correct_answer']
df_final

,pretext,options,correct answer
0,"Sentence : To add insult to injury, a boy was ...","[To make things worse, a boy was leading a han...","To make things worse, a boy was leading a hand..."
1,"Sentence : Oh, you know how it is, mother, whe...","[Oh, you know how it is, mother, when you spen...","Oh, you know how it is, mother, when you spend..."
2,"Sentence : Definitely a good person, but one c...","[Definitely a good person, but one could tell ...","Definitely a good person, but one could tell s..."
3,Sentence : To ask what's it like to be a warde...,"[To ask what's it like to be a warden in d.c.,...","To ask what's it like to be a warden in d.c., ..."
4,Sentence : He would smash into it at full tilt.,"[He would smash into it as fast as he could., ...",He would smash into it as fast as he could.
...,...,...,...
1765,Sentence : You're loyal as Benedict Arnold,"[You're disloyal, You're loyal]",You're disloyal
1766,Sentence : The cat was as white as charcoal,"[The cat was white, The cat was black]",The cat was black
1767,Sentence : You're as thin as a balloon,"[You're thin, You're fat]",You're fat
1768,Sentence : The woman was as useful as People M...,"[The woman was useless., The woman was useful.]",The woman was useless.
1769,Sentence : The conversation was as juicy as a ...,"[The conversation was very juicy., The convers...",The conversation was very dull.

In [143]:
df_final.to_csv("./../global_datasets/task_6.csv")

In [144]:
df_final1 = pd.DataFrame()
df_final1['pretext'] = 'Sentence : ' + filtered_df['hypothesis'] + '\nHint : '+filtered_df['entailed_exp']
df_final1['options'] = [[filtered_df['meaning1'][i],filtered_df['meaning2'][i]] for i in range(len(filtered_df))]
df_final1['correct answer'] = filtered_df['correct_answer']
df_final1

,pretext,options,correct answer
0,"Sentence : To add insult to injury, a boy was ...","[To make things worse, a boy was leading a han...","To make things worse, a boy was leading a hand..."
1,"Sentence : Oh, you know how it is, mother, whe...","[Oh, you know how it is, mother, when you spen...","Oh, you know how it is, mother, when you spend..."
2,"Sentence : Definitely a good person, but one c...","[Definitely a good person, but one could tell ...","Definitely a good person, but one could tell s..."
3,Sentence : To ask what's it like to be a warde...,"[To ask what's it like to be a warden in d.c.,...","To ask what's it like to be a warden in d.c., ..."
4,Sentence : He would smash into it at full tilt...,"[He would smash into it as fast as he could., ...",He would smash into it as fast as he could.
...,...,...,...
1765,Sentence : You're loyal as Benedict Arnold\nHi...,"[You're disloyal, You're loyal]",You're disloyal
1766,Sentence : The cat was as white as charcoal\nH...,"[The cat was white, The cat was black]",The cat was black
1767,Sentence : You're as thin as a balloon\nHint :...,"[You're thin, You're fat]",You're fat
1768,Sentence : The woman was as useful as People M...,"[The woman was useless., The woman was useful.]",The woman was useless.
1769,Sentence : The conversation was as juicy as a ...,"[The conversation was very juicy., The convers...",The conversation was very dull.

In [145]:
df_final1.to_csv("./../global_datasets/task_7.csv")

In [146]:
df_final2 = pd.DataFrame()
df_final2['pretext'] = 'Sentence : ' + filtered_df['hypothesis'] + '\nHint : '+filtered_df['contradictory_exp']
df_final2['options'] = [[filtered_df['meaning1'][i],filtered_df['meaning2'][i]] for i in range(len(filtered_df))]
df_final2['correct answer'] = filtered_df['correct_answer']
df_final2

,pretext,options,correct answer
0,"Sentence : To add insult to injury, a boy was ...","[To make things worse, a boy was leading a han...","To make things worse, a boy was leading a hand..."
1,"Sentence : Oh, you know how it is, mother, whe...","[Oh, you know how it is, mother, when you spen...","Oh, you know how it is, mother, when you spend..."
2,"Sentence : Definitely a good person, but one c...","[Definitely a good person, but one could tell ...","Definitely a good person, but one could tell s..."
3,Sentence : To ask what's it like to be a warde...,"[To ask what's it like to be a warden in d.c.,...","To ask what's it like to be a warden in d.c., ..."
4,Sentence : He would smash into it at full tilt...,"[He would smash into it as fast as he could., ...",He would smash into it as fast as he could.
...,...,...,...
1765,Sentence : You're loyal as Benedict Arnold\nHi...,"[You're disloyal, You're loyal]",You're disloyal
1766,Sentence : The cat was as white as charcoal\nH...,"[The cat was white, The cat was black]",The cat was black
1767,Sentence : You're as thin as a balloon\nHint :...,"[You're thin, You're fat]",You're fat
1768,Sentence : The woman was as useful as People M...,"[The woman was useless., The woman was useful.]",The woman was useless.
1769,Sentence : The conversation was as juicy as a ...,"[The conversation was very juicy., The convers...",The conversation was very dull.

In [147]:
df_final2.to_csv("./../global_datasets/task_8.csv")

In [102]:
df_final2.reset_index(drop=True,inplace=True)

In [103]:
duplicate_rows = df_final[df_final2.duplicated(subset=['meaning1','meaning2'], keep=False)]
len(duplicate_rows)

KeyError: Index(['meaning1', 'meaning2'], dtype='object')

In [107]:
li  = [i[0]==i[1] for i in df_final['options']]

In [111]:
df_final[li]['options'][583]

["The key will be unclaimed and available to anyone, but he 'll be too weak to make a play for it, leaving the field wide open for you.",
 "The key will be unclaimed and available to anyone, but he 'll be too weak to make a play for it, leaving the field wide open for you."]

In [119]:
filtered_df['meaning1'][583]==filtered_df['meaning2'][583]

True

"The key will be unclaimed and available to anyone, but he 'll be too weak to make a play for it, leaving the field wide open for you."

In [118]:
temp = filtered_df.loc[583]
for k in temp:
    print(k)

The key will be up for grabs, but he 'll be too weak to make a play for it, leaving the field wide open for you.
Up for grabs means available to anyone, and in this context the key is unclaimed and available to anyone.
Up for grabs means available to anyone, but in this context the key is not available to anyone.
The key will be unclaimed and available to anyone, but he 'll be too weak to make a play for it, leaving the field wide open for you.
The key will be unclaimed and available to anyone, but he 'll be too weak to make a play for it, leaving the field wide open for you.
The key will be unclaimed and available to anyone, but he 'll be too weak to make a play for it, leaving the field wide open for you.